name: Test Project
on: push 
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: action/checkout@v3
            - name: Install nodeJs
              uses: action/steps-node@v3
              with:
                node-version: 18
            - name: Install dependinces
              run: npm ci
            -name:Run test
              run: npm test
